In [3]:
import numpy as np

In [7]:
lista_numeros = [10, 20, 30]
print(lista_numeros)

vetor_numeros = np.array( [10, 20, 30, 40, 50, 60, 70] )
print(vetor_numeros)

[10, 20, 30]
[10 20 30 40 50 60 70]


In [ ]:
# 20000 + 4 * 6 = 20024

In [9]:
vetor_numeros[1] = 25

In [11]:
vetor_numeros

array([10, 25, 30, 40, 50, 60, 70])

In [29]:
# [10, 25, 30, 40, 50, 60, 70] + [10, 25, 30, 40, 50, 60, 70]
vetor_numeros + vetor_numeros

array([ 20,  50,  60,  80, 100, 120, 140])

In [27]:
np.concatenate( vetor_numeros, vetor_numeros)

TypeError: only integer scalar arrays can be converted to a scalar index

In [31]:
vetor_numeros * 7

array([ 70, 175, 210, 280, 350, 420, 490])

In [33]:
vetor_numeros.dtype

dtype('int32')

In [35]:
vetor_numeros[1] = 25.6

In [41]:
outor_vetor = vetor_numeros.astype(np.float32)

In [43]:
outor_vetor

array([10., 25., 30., 40., 50., 60., 70.], dtype=float32)

In [49]:
outor_vetor[1] = 35.6

In [51]:
outor_vetor

array([10. , 35.6, 30. , 40. , 50. , 60. , 70. ], dtype=float32)

In [53]:
vetor_numeros

array([10, 25, 30, 40, 50, 60, 70])

In [57]:
vetor_numeros.dtype

dtype('int32')

In [59]:
vetor_numeros.ndim

1

In [61]:
vetor_numeros.shape

(7,)

In [75]:
matriz1 = np.array( [ [10, 20], [40, 50], [60, 70] ], dtype=np.float32)

In [77]:
matriz1.dtype

dtype('float32')

In [79]:
matriz1.ndim

2

In [81]:
matriz1.shape

(3, 2)

In [83]:
matriz1

array([[10., 20.],
       [40., 50.],
       [60., 70.]], dtype=float32)

In [87]:
scalar = np.array( 108 ) 

In [89]:
scalar.ndim

0

In [91]:
scalar.shape

()

In [93]:
scalar.dtype

dtype('int32')

In [101]:
matriz2 = np.zeros( (20, 10) )
matriz2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [111]:
vetor3 = np.arange( -10, 10, 0.5 )
vetor3

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [115]:
vetor4 = np.concatenate( [vetor3, [10]] )
vetor4

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5,  10. ])

In [121]:
vetor4.shape

(41,)

In [123]:
np.zeros_like(vetor4)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [125]:
matriz1

array([[10., 20.],
       [40., 50.],
       [60., 70.]], dtype=float32)

In [129]:
np.ones_like(matriz1)

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [155]:
# np.random.random( (7, 3) )
matriz5 = np.random.randint( 10, 20, (7, 3) )

In [147]:
matriz_ident_6 = np.eye(6)
matriz_ident_6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [151]:
matriz_ident_6.reshape( (9, 4) )

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [153]:
matriz_ident_6.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [157]:
matriz5

array([[16, 18, 15],
       [11, 11, 18],
       [18, 14, 12],
       [14, 18, 16],
       [10, 12, 15],
       [14, 17, 16],
       [12, 10, 17]])

In [159]:
matriz5.T

array([[16, 11, 18, 14, 10, 14, 12],
       [18, 11, 14, 18, 12, 17, 10],
       [15, 18, 12, 16, 15, 16, 17]])

In [195]:
matriz6 = np.random.randint( 10, 30, (6, 4) )
matriz6

array([[10, 27, 11, 23],
       [20, 22, 18, 17],
       [14, 24, 28, 11],
       [27, 17, 13, 28],
       [14, 24, 28, 26],
       [21, 21, 13, 15]])

In [197]:
matriz6.reshape(24)

array([10, 27, 11, 23, 20, 22, 18, 17, 14, 24, 28, 11, 27, 17, 13, 28, 14,
       24, 28, 26, 21, 21, 13, 15])

In [199]:
matriz6.T

array([[10, 20, 14, 27, 14, 21],
       [27, 22, 24, 17, 24, 21],
       [11, 18, 28, 13, 28, 13],
       [23, 17, 11, 28, 26, 15]])

In [201]:
matriz6.ravel()

array([10, 27, 11, 23, 20, 22, 18, 17, 14, 24, 28, 11, 27, 17, 13, 28, 14,
       24, 28, 26, 21, 21, 13, 15])

In [219]:
matriz6

array([[-19,  27,  11,  23],
       [ 20,  22,  18,  17],
       [ 14,  24,  28,  11],
       [ 27,  17,  13,  28],
       [ 14,  24,  28,  26],
       [ 21,  21,  13,  15]])

In [213]:
matriz7 = np.copy(matriz6.reshape(3, 8))
matriz7

array([[-19,  27,  11,  23,  20,  22,  18,  17],
       [ 14,  24,  28,  11,  27,  17,  13,  28],
       [ 14,  24,  28,  26,  21,  21,  13,  15]])

In [217]:
matriz7[0, 0] = 19
matriz7

array([[19, 27, 11, 23, 20, 22, 18, 17],
       [14, 24, 28, 11, 27, 17, 13, 28],
       [14, 24, 28, 26, 21, 21, 13, 15]])

In [221]:
np.savez( "matriz7.npz", a=matriz7 )

NameError: name 'matriz7' is not defined

In [7]:
dados = np.load("matriz7.npz")
matriz7 = dados["a"]
matriz7

array([[19, 27, 11, 23, 20, 22, 18, 17],
       [14, 24, 28, 11, 27, 17, 13, 28],
       [14, 24, 28, 26, 21, 21, 13, 15]])

In [9]:
matriz7 + 4

array([[23, 31, 15, 27, 24, 26, 22, 21],
       [18, 28, 32, 15, 31, 21, 17, 32],
       [18, 28, 32, 30, 25, 25, 17, 19]])

In [13]:
matriz7 > 25

array([[False,  True, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False,  True],
       [False, False,  True,  True, False, False, False, False]])

In [15]:
matriz7 += 4

In [17]:
matriz7

array([[23, 31, 15, 27, 24, 26, 22, 21],
       [18, 28, 32, 15, 31, 21, 17, 32],
       [18, 28, 32, 30, 25, 25, 17, 19]])

In [23]:
matriz7[matriz7 > 25] = -10

In [25]:
matriz7

array([[ 23, -10,  15, -10,  24, -10,  22,  21],
       [ 18, -10, -10,  15, -10,  21,  17, -10],
       [ 18, -10, -10, -10,  25,  25,  17,  19]])

In [29]:
matriz8 = np.sqrt(matriz7)

C:\Users\anton\AppData\Local\Temp\ipykernel_40296\724613441.py:1: RuntimeWarning: invalid value encountered in sqrt
  matriz8 = np.sqrt(matriz7)


In [31]:
np.isnan( matriz8 )

array([[False,  True, False,  True, False,  True, False, False],
       [False,  True,  True, False,  True, False, False,  True],
       [False,  True,  True,  True, False, False, False, False]])

In [33]:
matriz8

array([[4.79583152,        nan, 3.87298335,        nan, 4.89897949,
               nan, 4.69041576, 4.58257569],
       [4.24264069,        nan,        nan, 3.87298335,        nan,
        4.58257569, 4.12310563,        nan],
       [4.24264069,        nan,        nan,        nan, 5.        ,
        5.        , 4.12310563, 4.35889894]])

In [47]:
matriz7

array([[ 23, -10,  15, -10,  24, -10,  22,  21],
       [ 18, -10, -10,  15, -10,  21,  17, -10],
       [ 18, -10, -10, -10,  25,  25,  17,  19]])

In [43]:
matriz7[ 1:-1, 1:-1]

array([[-10, -10,  15, -10,  21,  17]])

In [53]:
matriz7.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2